# Generated by Django 3.2.16 on 2023-04-20 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=50)),
                ('uzaklik', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('fiyat', models.IntegerField(null=True)),
                ('bilgi', models.TextField(max_length=150)),
                ('resim1', models.FileField(upload_to='postpic/')),
                ('resim2', models.FileField(upload_to='postpic/')),
                ('resim3', models.FileField(upload_to='postpic/')),
                ('resim4', models.FileField(upload_to='postpic/')),
                ('resim5', models.FileField(upload_to='postpic/')),
                ('evsahibi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.kategori')),
                ('like', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
