# Generated by Django 4.1.3 on 2023-04-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_profil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='email',
            new_name='telefon',
        ),
    ]
